# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Time_Save_Window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dateEdit_start = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_start.sizePolicy().hasHeightForWidth())
        self.dateEdit_start.setSizePolicy(sizePolicy)
        self.dateEdit_start.setCalendarPopup(True)
        self.dateEdit_start.setDate(QtCore.QDate(2019, 4, 19))
        self.dateEdit_start.setObjectName("dateEdit_start")
        self.gridLayout_2.addWidget(self.dateEdit_start, 1, 1, 1, 1)
        self.timeEdit_start = QtWidgets.QTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_start.sizePolicy().hasHeightForWidth())
        self.timeEdit_start.setSizePolicy(sizePolicy)
        self.timeEdit_start.setCalendarPopup(False)
        self.timeEdit_start.setTime(QtCore.QTime(17, 0, 0))
        self.timeEdit_start.setObjectName("timeEdit_start")
        self.gridLayout_2.addWidget(self.timeEdit_start, 0, 1, 1, 1)
        self.get_time_but_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_time_but_start.sizePolicy().hasHeightForWidth())
        self.get_time_but_start.setSizePolicy(sizePolicy)
        self.get_time_but_start.setMinimumSize(QtCore.QSize(0, 70))
        self.get_time_but_start.setMaximumSize(QtCore.QSize(173, 16777215))
        self.get_time_but_start.setObjectName("get_time_but_start")
        self.gridLayout_2.addWidget(self.get_time_but_start, 0, 0, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.set_but_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_but_start.sizePolicy().hasHeightForWidth())
        self.set_but_start.setSizePolicy(sizePolicy)
        self.set_but_start.setMaximumSize(QtCore.QSize(16777215, 30))
        self.set_but_start.setObjectName("set_but_start")
        self.horizontalLayout.addWidget(self.set_but_start)
        self.reset_but_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_but_start.sizePolicy().hasHeightForWidth())
        self.reset_but_start.setSizePolicy(sizePolicy)
        self.reset_but_start.setMaximumSize(QtCore.QSize(16777215, 30))
        self.reset_but_start.setObjectName("reset_but_start")
        self.horizontalLayout.addWidget(self.reset_but_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dateEdit_stop = QtWidgets.QDateEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_stop.sizePolicy().hasHeightForWidth())
        self.dateEdit_stop.setSizePolicy(sizePolicy)
        self.dateEdit_stop.setCalendarPopup(True)
        self.dateEdit_stop.setDate(QtCore.QDate(2019, 4, 19))
        self.dateEdit_stop.setObjectName("dateEdit_stop")
        self.gridLayout_3.addWidget(self.dateEdit_stop, 1, 1, 1, 1)
        self.timeEdit_stop = QtWidgets.QTimeEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit_stop.sizePolicy().hasHeightForWidth())
        self.timeEdit_stop.setSizePolicy(sizePolicy)
        self.timeEdit_stop.setCalendarPopup(False)
        self.timeEdit_stop.setTime(QtCore.QTime(17, 0, 0))
        self.timeEdit_stop.setObjectName("timeEdit_stop")
        self.gridLayout_3.addWidget(self.timeEdit_stop, 0, 1, 1, 1)
        self.get_time_but_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_time_but_stop.sizePolicy().hasHeightForWidth())
        self.get_time_but_stop.setSizePolicy(sizePolicy)
        self.get_time_but_stop.setMinimumSize(QtCore.QSize(0, 70))
        self.get_time_but_stop.setMaximumSize(QtCore.QSize(173, 16777215))
        self.get_time_but_stop.setObjectName("get_time_but_stop")
        self.gridLayout_3.addWidget(self.get_time_but_stop, 0, 0, 2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.set_but_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_but_stop.sizePolicy().hasHeightForWidth())
        self.set_but_stop.setSizePolicy(sizePolicy)
        self.set_but_stop.setMaximumSize(QtCore.QSize(16777215, 30))
        self.set_but_stop.setObjectName("set_but_stop")
        self.horizontalLayout_3.addWidget(self.set_but_stop)
        self.reset_but_stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_but_stop.sizePolicy().hasHeightForWidth())
        self.reset_but_stop.setSizePolicy(sizePolicy)
        self.reset_but_stop.setMaximumSize(QtCore.QSize(16777215, 30))
        self.reset_but_stop.setObjectName("reset_but_stop")
        self.horizontalLayout_3.addWidget(self.reset_but_stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.save_but = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_but.sizePolicy().hasHeightForWidth())
        self.save_but.setSizePolicy(sizePolicy)
        self.save_but.setMinimumSize(QtCore.QSize(250, 0))
        self.save_but.setMaximumSize(QtCore.QSize(16777215, 40))
        self.save_but.setObjectName("save_but")
        self.horizontalLayout_2.addWidget(self.save_but)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "START"))
        self.timeEdit_start.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.get_time_but_start.setText(_translate("MainWindow", "Get time"))
        self.set_but_start.setText(_translate("MainWindow", "Set"))
        self.reset_but_start.setText(_translate("MainWindow", "Reset"))
        self.label_3.setText(_translate("MainWindow", "STOP"))
        self.timeEdit_stop.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.get_time_but_stop.setText(_translate("MainWindow", "Get time"))
        self.set_but_stop.setText(_translate("MainWindow", "Set"))
        self.reset_but_stop.setText(_translate("MainWindow", "Reset"))
        self.save_but.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

